### PR TITLE
Fix Create New + button; improve header selectors

### LINKED ISSUE #70: Create new button is white
The "Create new" button in the header is white when using the grey header.

### PR DESCRIPTION
**Pull request by joeytwiddle**
Closes #70

### CODE REVIEW

File: src/content_script.js [hunk 1]
```diff
@@ -2,7 +2,10 @@ var headerBar;
 
 function initOnce () {
     // check if element exists yet
-    headerBar = document.querySelector('body > div > .Header');
+    // GitHub history: header, then header.Header, now header.Header-old
+    // Gist history: header, then .Header, now .Header-old
+    //headerBar = document.querySelector('body > div > header, body > div > .Header, body > div > .Header-old');
+    headerBar = document.querySelector('header, .Header, .Header-old');
```
Comment (joeytwiddle) [inline src/content_script.js]: I went for a more generalised selector, in case they change or move the headers in future.

I'm not aware of any secondary `header` elements deeper on GitHub pages which we should avoid. Are there any?
